---
specfile_path: fedora/systemd.spec
synced_files:
  - fedora/
  - .packit.yaml
downstream_package_name: systemd

jobs:
- job: sync_from_downstream
  trigger: commit
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-29-x86_64
upstream_ref: 239.stable.feb.2019
